# filepath: /data/seekyou/Algos/MGCL/config.yaml
logpath: demo
gpuid: 0
bsz: 16
epoch_num: 100
fold: 0
backbone: resnet50
finetune_backbone: true
mask: true
mask_num: 128
datapath: /data/seekyou/Data/7class_LCML/Maping4DLRSD
benchmark: lcma_plus
lr: 0.001
power: 0.9
niter: 100
max_steps: 200000
nworker: 8
img_size: 256
use_original_imgsize: false
net_name: MG_FBC_3Network
is_sgd: False
use_gpu: true
shot: 1