# filepath: /data/seekyou/Algos/MGCL/config.yaml
logpath: demo
gpuid: 0
bsz: 16
epoch_num: 50
fold: 2
backbone: resnet50
finetune_backbone: true
mask: true
mask_num: 128
datapath: /data/seekyou/Data/iSAID
benchmark: isaid
lr: 0.01
power: 0.9
max_steps: 200000
nworker: 8
img_size: 256
use_original_imgsize: false
net_name: MG_FBC_3_v2Network
is_sgd: True
use_gpu: true
shot: 1
